"""Rendering — the compact review artifact and the console progress lines.

``REVIEW.md`` is ordered by what deserves attention: the review queue first
(with a full-note detail block per row, so review needs no re-fetch), then the
pre-greened fills ready to author, then the auto-audited tallies. A reviewer
skims a short table, not a dying chat transcript.
"""

from __future__ import annotations

from collections import Counter
from typing import TYPE_CHECKING

from ai_corpus_sweep import gate

if TYPE_CHECKING:
    from collections.abc import Iterable, Sequence

    from ai_corpus_sweep.sweep import SweepRow

# Review dispositions in the order a human should meet them: catalog-wrong
# candidates first, then disagreements and doubt, then mechanical failures.
_REVIEW_ORDER = (
    gate.CONFLICT,
    gate.SET_BUT_UNSUPPORTED,
    gate.FACTS_MISMATCH,
    gate.SAME_MAKER,
    gate.QUOTE_UNSUPPORTED,
    gate.MULTI_TARGET,
    gate.HINT_MISMATCH,
    gate.AMBIGUOUS,
    gate.UNRESOLVED,
    gate.UNCERTAIN,
    gate.QUOTE_FAIL,
    gate.NO_MODEL,
    gate.NO_EVIDENCE,
    gate.AI_ERROR,
)


def _md(text: str) -> str:
    """Escape the characters that would break a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ")


def _row_label(row: SweepRow) -> str:
    slug = f"`{row.model_slug}`" if row.model_slug else "(no model)"
    return f"ipdb:{row.ipdb_id} {slug} {row.field}"


def progress_line(done: int, total: int, row: SweepRow) -> str:
    """One console line per judged row — the run narrates itself."""
    outcome = row.disposition
    if row.resolved_slug:
        outcome += f" → {row.resolved_slug}"
    return f"[{done}/{total}] {_row_label(row)}: {outcome}"


def _counts_table(rows: Sequence[SweepRow]) -> list[str]:
    counts = Counter(row.disposition for row in rows)
    lines = ["| disposition | rows |", "| --- | ---: |"]
    ordered = [*_REVIEW_ORDER, gate.FILL, gate.AGREES, gate.NO_CLAIM]
    lines.extend(
        f"| {'🟢' if disposition in gate.GREEN else '⚠️'} {disposition} "
        f"| {counts[disposition]} |"
        for disposition in ordered
        if counts[disposition]
    )
    lines.append(f"| **total** | **{len(rows)}** |")
    return lines


def _review_detail(row: SweepRow) -> list[str]:
    """The full-context block for one review row."""
    lines = [f"### {_row_label(row)} — {row.disposition}", ""]
    facts = [
        ("model", f"`{row.model_slug}` ({row.model_name})" if row.model_slug else "—"),
        ("catalog now", f"`{row.catalog_now}`" if row.catalog_now else "(empty)"),
        ("prior guess", f"`{row.hint}`" if row.hint else "—"),
        ("verdict", row.verdict or "—"),
    ]
    if row.target_title:
        stated = row.target_title
        extras = ", ".join(
            bit for bit in (row.target_maker, str(row.target_year or "") or None) if bit
        )
        facts.append(
            ("note states target", f"{stated} ({extras})" if extras else stated)
        )
    if row.resolved_slug:
        facts.append(("resolved", f"`{row.resolved_slug}`"))
    if row.resolution_how:
        facts.append(("resolution", row.resolution_how))
    lines.extend(f"- **{key}:** {value}" for key, value in facts)
    if row.considered:
        lines.append("- **candidates considered:**")
        lines.extend(f"  - {item}" for item in row.considered)
    lines.extend(f"- **why here:** {reason}" for reason in row.reasons)
    if row.quote:
        mark = "✓ verbatim" if row.quote_verified else "✗ NOT verbatim"
        source = f" in {row.quote_ref}" if row.quote_ref else ""
        lines.append(f"- **quote ({mark}{source}):** “{row.quote}”")
    for ref, text in row.evidence:
        lines.append("")
        lines.append(f"> **{ref}:** {text.strip()}".replace("\n", "\n> "))
    lines.append("")
    return lines


def _fill_line(row: SweepRow) -> str:
    mark = "✓" if row.quote_verified else "✗"
    ref = row.quote_ref or (row.evidence[0][0] if row.evidence else "?")
    return (
        f"- {_row_label(row)} → `{row.resolved_slug}` — quote {mark} ({ref}): "
        f"“{row.quote}”"
    )


def render_review(rows: Sequence[SweepRow]) -> str:
    """The whole REVIEW.md for a run's rows (resumed rows included)."""
    out: list[str] = [
        "# Corpus sweep review",
        "",
        "_Generated by `ai_corpus_sweep`. Review rows carry their full source "
        "note(s); `results.json` beside this file holds every row, machine-"
        "readable. Regenerate by re-running the sweep with `--resume`._",
        "",
        "## Totals",
        "",
        *_counts_table(rows),
        "",
    ]

    # Per-maker roster: the campaign's unit of work is one patch per maker, and
    # completing a maker needs its ESCALATED rows too, not just its fills.
    by_roster_maker: dict[str, list[SweepRow]] = {}
    for row in rows:
        by_roster_maker.setdefault(row.maker or "(maker unknown)", []).append(row)
    out += [
        "## Per-maker roster",
        "",
        "| maker | fill | green | needs review |",
        "| --- | ---: | ---: | --- |",
    ]
    for maker, maker_rows in sorted(
        by_roster_maker.items(), key=lambda kv: (-len(kv[1]), kv[0])
    ):
        fills_n = sum(1 for r in maker_rows if r.disposition == gate.FILL)
        green_n = sum(
            1
            for r in maker_rows
            if r.disposition in gate.GREEN and r.disposition != gate.FILL
        )
        escalated = Counter(r.disposition for r in maker_rows if r.needs_review)
        detail = ", ".join(f"{d} {n}" for d, n in escalated.most_common()) or "—"
        out.append(f"| `{maker}` | {fills_n} | {green_n} | {detail} |")
    out.append("")

    review_rows = [row for row in rows if row.needs_review]
    if review_rows:
        out += [f"## Needs review ({len(review_rows)})", ""]
        for disposition in _REVIEW_ORDER:
            for row in review_rows:
                if row.disposition == disposition:
                    out.extend(_review_detail(row))

    fills = [row for row in rows if row.disposition == gate.FILL]
    if fills:
        # Grouped by the subject's maker — the campaign's authoring unit is one
        # patch per maker, so the grouping is the author's work plan.
        by_maker: dict[str, list[SweepRow]] = {}
        for row in fills:
            by_maker.setdefault(row.maker or "(maker unknown)", []).append(row)
        out += [
            f"## Ready to author — catalog empty, quote verified, unique target "
            f"({len(fills)}, one patch per maker)",
            "",
        ]
        for maker, maker_rows in sorted(
            by_maker.items(), key=lambda kv: (-len(kv[1]), kv[0])
        ):
            out += [f"### {maker} ({len(maker_rows)})", ""]
            # Two same-maker fills onto ONE target are an un-authorable slug
            # collision (the rmg space-orbit pair) — a joint decision, not two
            # independent rows; warn before an author walks into it.
            by_target: dict[str, list[SweepRow]] = {}
            for row in maker_rows:
                if row.resolved_slug:
                    by_target.setdefault(row.resolved_slug, []).append(row)
            for target, shared in sorted(by_target.items()):
                if len(shared) > 1:
                    who = ", ".join(f"`{row.model_slug}`" for row in shared)
                    out.append(
                        f"- ⚠ **shared target `{target}`**: {who} — a same-name "
                        "merge/slug decision is needed jointly, before "
                        "authoring these rows independently"
                    )
            out += [*(_fill_line(row) for row in maker_rows), ""]

    agrees = [row for row in rows if row.disposition == gate.AGREES]
    if agrees:
        out += [
            f"## Catalog confirmed — note independently supports the existing "
            f"value ({len(agrees)})",
            "",
            *(
                f"- {_row_label(row)}: `{row.catalog_now}`"
                + (f" — {row.reasons[0]}" if row.reasons else "")
                for row in agrees
            ),
            "",
        ]

    no_claims = [row for row in rows if row.disposition == gate.NO_CLAIM]
    if no_claims:
        out += [
            f"## Net false positives — note supports no claim ({len(no_claims)})",
            "",
            *(
                f"- {_row_label(row)}"
                + (f" — {_md(row.reasons[0])}" if row.reasons else "")
                for row in no_claims
            ),
            "",
        ]
    return "\n".join(out)


def render_status(rows: Sequence[SweepRow], total_candidates: int) -> str:
    """A one-screen answer to "what is the run doing?" — from results.json alone.

    Readable at any time, by anyone, without touching the running process:
    the artifact on disk IS the status. (The operator is usually a human
    behind an AI session; stderr never reaches them.)
    """
    counts = Counter(row.disposition for row in rows)
    review = sum(1 for row in rows if row.needs_review)
    pending = max(0, total_candidates - len(rows))
    lines = [
        f"judged {len(rows)}/{total_candidates} candidates"
        + (f" — {pending} pending" if pending else " — run complete"),
        f"needs review: {review}",
        "dispositions: "
        + (
            ", ".join(f"{d} {n}" for d, n in counts.most_common())
            if counts
            else "(none yet)"
        ),
    ]
    return "\n".join(lines)


def render_reconcile(rows: Iterable[SweepRow]) -> str:
    """The free, no-AI preview: what the catalog already settles.

    Buckets every candidate against the live catalog only — no judgment of the
    notes. Its job is (a) a wiring check before spending, and (b) coverage at
    a glance.
    """
    listed = list(rows)
    by_bucket: dict[str, list[SweepRow]] = {}
    for row in listed:
        by_bucket.setdefault(row.disposition, []).append(row)

    out = [
        "# Corpus sweep reconcile (no AI)",
        "",
        "_Candidates diffed against the live catalog only; the notes are not "
        "judged. `set` rows would still be re-judged by a full sweep — that is "
        "what catches wrong existing values._",
        "",
        "| bucket | rows |",
        "| --- | ---: |",
        *(
            f"| {bucket} | {len(bucket_rows)} |"
            for bucket, bucket_rows in sorted(by_bucket.items())
        ),
        f"| **total** | **{len(listed)}** |",
        "",
    ]
    mismatches = [
        row
        for row in listed
        if row.catalog_now and row.hint and row.catalog_now != row.hint
    ]
    if mismatches:
        out += [
            "## Set rows whose catalog target ≠ the prior guess — a sweep "
            "would adjudicate these",
            "",
            "| row | catalog now | prior guess |",
            "| --- | --- | --- |",
            *(
                f"| {_row_label(row)} | `{row.catalog_now}` | `{row.hint}` |"
                for row in mismatches
            ),
            "",
        ]
    missing = by_bucket.get(gate.NO_MODEL, [])
    if missing:
        out += [
            "## Candidates with no catalog model (ipdb_id not found)",
            "",
            *(f"- ipdb:{row.ipdb_id} ({row.field})" for row in missing),
            "",
        ]
    return "\n".join(out)
