-- A layer that compares the Flipcommons catalog against external data sources like
-- IPDB and OPDB. `.read` this from a campaign analysis after flipcommons' foundation:
--
--     .read ../flippatch/scripts/analysis/external_data_sources.sql
--
-- BAKED. The directive below registers the layer with the analysis runner, which
-- rebakes external_data_sources.duckdb whenever an input changes — the catalog
-- snapshot, pinexplore's explore.duckdb, or any file under external_data_sources/ —
-- and regenerates the pass-through shim read here. The layer's source SQL is
-- external_data_sources/_build.sql and executes only at bake time; a query session
-- opens finished tables read-only, so this read costs milliseconds, not the analysis.
-- Note `px` is therefore attached at bake time only — a campaign wanting pinexplore's
-- dumps raw attaches explore.duckdb itself, as 0268/0269/0277/0278 do.
-- Freshness is guaranteed only through the runner (make analyze); raw `duckdb`
-- sessions read whatever the last bake produced.
-- A session editing one source deeply still `.read`s that source's file under
-- external_data_sources/ directly — live SQL is the point there (PREFIX=<source>).
-- layer: ../flippatch/scripts/analysis/external_data_sources.layer
.read ../flippatch/scripts/analysis/external_data_sources.gen.sql
